server:
  port: 18090
spring:
  application:
    name: pay
  main:
    allow-bean-definition-overriding: true
  rabbitmq:
    host: 192.168.211.132
    port: 5672
#配置支付交换机和队列
mq:
  pay:
    exchange:
      order: exchange.order
      seckillorder: exchange.seckillorder
    queue:
      order: queue.order
      seckillorder: queue.seckillorder
    routing:
      key: queue.order
      seckillkey: queue.seckillorder
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true
#hystrix 配置
hystrix:
  command:
    default:
      execution:
        timeout:
        #如果enabled设置为false，则请求超时交给ribbon控制
          enabled: true
        isolation:
          strategy: SEMAPHORE

#微信支付信息配置
weixin:
  #微信公众账号或开放平台APP的唯一标识
  appid: wx8397f8696b538317
  #财付通平台的商户账号
  partner: 1473426802
  #财付通平台的商户密钥
  partnerkey: T6m9iK73b0kn9g5v426MKfHQH7X8rKwb
  #回调地址
  notifyurl: 2991il4535.wicp.vip:19388/weixin/pay/notify/url